create table cliente (id int8 generated by default as identity, bairro varchar(255) not null, cep varchar(255) not null, cidade varchar(255) not null, logradouro varchar(255) not null, nome varchar(255) not null, numero int4 not null, telefone varchar(255) not null, uf varchar(2) not null, primary key (id));
create table pet (id int8 generated by default as identity, cor_do_pelo varchar(255), nome varchar(255), cliente_id int8, raca_id int8, primary key (id));
create table raca (id int8 generated by default as identity, tipo_raca varchar(255), primary key (id));
alter table if exists cliente add constraint UK_cjamibneobl928lfs71yos48r unique (telefone);
alter table if exists raca add constraint UK_cirqexkpo9rxorq7qup55idgu unique (tipo_raca);
alter table if exists pet add constraint FKk6kdsulmc6jsvoo9tl5oachcw foreign key (cliente_id) references cliente;
alter table if exists pet add constraint FKphlx97x2qjac80q4hr69bvyif foreign key (raca_id) references raca;